/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:dd643941-206d-4bb2-8061-9b81f296dcae",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_joMcBXxAm",
    "aws_user_pools_web_client_id": "57oi8uhpo5ounath19osheu5bp",
    "oauth": {}
};


export default awsmobile;
